Repository icn-team/android-sdk, pull requests merged in 2019-12, with the labels that each got.

#14 Fix proxy destruction
  HicnForwarderAndroid/app/src/main/java/com/cisco/hicn/forwarder/service/BackendProxyService.java
  HicnForwarderAndroid/app/src/main/java/com/cisco/hicn/forwarder/service/ProxyThread.java
  HicnForwarderAndroid/app/src/main/jni/hproxy-wrapper.cpp
  scripts/init.sh
Labels: bug

#16 Fix udp tunnel configuration, by adding the connector name.
  HicnForwarderAndroid/app/src/main/jni/hproxy-wrapper.cpp
Labels: bug

#19 Added hicn-light-control tutorial
  README.md
Labels: documentation

#21 Add API for closing tun fd.
  HicnForwarderAndroid/app/src/main/java/com/cisco/hicn/forwarder/service/BackendProxyService.java
  HicnForwarderAndroid/app/src/main/java/com/cisco/hicn/forwarder/service/ProxyThread.java
  HicnForwarderAndroid/app/src/main/java/com/cisco/hicn/forwarder/supportlibrary/HProxy.java
  HicnForwarderAndroid/app/src/main/jni/hproxy-wrapper.cpp
Labels: enhancement

#24 Correct jni exception: do not use global variables for hProxy instance.
  HicnForwarderAndroid/app/src/main/java/com/cisco/hicn/forwarder/forwarder/ForwarderFragment.java
  HicnForwarderAndroid/app/src/main/java/com/cisco/hicn/forwarder/preferences/PreferencesFragment.java
  HicnForwarderAndroid/app/src/main/java/com/cisco/hicn/forwarder/service/BackendProxyService.java
  HicnForwarderAndroid/app/src/main/java/com/cisco/hicn/forwarder/service/ProxyThread.java
  HicnForwarderAndroid/app/src/main/java/com/cisco/hicn/forwarder/supportlibrary/HProxy.java
  HicnForwarderAndroid/app/src/main/jni/hproxy-wrapper.cpp
Labels: enhancement
